version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: 0EwubBWgT3ydBznRpUBqN7ZfcN2VvOD/KR2y29Iel51nHOqrC5s66QVljHOylVom
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master