version: 1.0.{build}
image: Visual Studio 2017
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: MIyGqXljiFUbmq/3pnUBZWPlTEwio0sKBhc8Ped38rfwc+LCQ+ZWyGI5A5pVK315
  skip_symbols: true
  artifact: /.*\.nupkg/
  on:
    branch: master